
spring.datasource.url=jdbc:mysql://localhost:3306/code_executor
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update

spring.redis.host=redis
spring.redis.port=6379
